package com.esiri.esiriplus.core.domain.model

data class PatientReport(
    val reportId: String,
    val consultationId: String,
    val patientSessionId: String,
    val reportUrl: String,
    val localFilePath: String? = null,
    val generatedAt: Long,
    val downloadedAt: Long? = null,
    val fileSizeBytes: Long,
    val isDownloaded: Boolean = false,
    val doctorName: String = "",
    val consultationDate: Long = 0L,
    val diagnosedProblem: String = "",
    val category: String = "",
    val severity: String = "",
    val presentingSymptoms: String = "",
    val diagnosisAssessment: String = "",
    val treatmentPlan: String = "",
    val followUpInstructions: String = "",
    val followUpRecommended: Boolean = false,
    val furtherNotes: String = "",
    val verificationCode: String = "",
)
