'use client';

import { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import {
  UserPlus, KeyRound, HelpCircle, Copy, CheckCircle2, AlertTriangle,
  ChevronRight, Shield, ArrowRight,
} from 'lucide-react';
import { Button, Input, Card, Select } from '@/components/ui';
import { invokeEdgeFunction } from '@/lib/supabase';
import { useAuthStore } from '@/store/auth';
// Types built inline from edge function responses

const AGE_GROUPS = [
  { value: '0-5', label: '0-5 years (Infant/Toddler)' },
  { value: '6-12', label: '6-12 years (Child)' },
  { value: '13-17', label: '13-17 years (Teenager)' },
  { value: '18-25', label: '18-25 years (Young Adult)' },
  { value: '26-35', label: '26-35 years' },
  { value: '36-45', label: '36-45 years' },
  { value: '46-55', label: '46-55 years' },
  { value: '56-65', label: '56-65 years' },
  { value: '65+', label: '65+ years (Senior)' },
];

const SEX_OPTIONS = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
];

const REGIONS = [
  { value: 'dar_es_salaam', label: 'Dar es Salaam' },
  { value: 'dodoma', label: 'Dodoma' },
  { value: 'arusha', label: 'Arusha' },
  { value: 'mwanza', label: 'Mwanza' },
  { value: 'kilimanjaro', label: 'Kilimanjaro' },
  { value: 'tanga', label: 'Tanga' },
  { value: 'morogoro', label: 'Morogoro' },
  { value: 'mbeya', label: 'Mbeya' },
  { value: 'iringa', label: 'Iringa' },
  { value: 'kagera', label: 'Kagera' },
  { value: 'tabora', label: 'Tabora' },
  { value: 'kigoma', label: 'Kigoma' },
  { value: 'shinyanga', label: 'Shinyanga' },
  { value: 'mara', label: 'Mara' },
  { value: 'songwe', label: 'Songwe' },
  { value: 'rukwa', label: 'Rukwa' },
  { value: 'ruvuma', label: 'Ruvuma' },
  { value: 'singida', label: 'Singida' },
  { value: 'lindi', label: 'Lindi' },
  { value: 'mtwara', label: 'Mtwara' },
  { value: 'pwani', label: 'Pwani (Coast)' },
  { value: 'geita', label: 'Geita' },
  { value: 'katavi', label: 'Katavi' },
  { value: 'simiyu', label: 'Simiyu' },
  { value: 'njombe', label: 'Njombe' },
  { value: 'zanzibar', label: 'Zanzibar' },
  { value: 'other', label: 'Other / Outside Tanzania' },
];

const TERMS_TABS = [
  {
    key: 'privacy', title: 'Privacy Policy',
    sections: [
      { heading: 'PRIVACY POLICY', body: 'Last Updated: February 2026' },
      { heading: 'We Built eSIRI Plus Around Your Privacy', body: "Most healthcare apps ask for your name, phone number, email, and ID. We don't. eSIRI Plus was designed from the ground up so that you can access quality healthcare in Tanzania without revealing who you are. Your health is personal \u2014 and it should stay that way." },
      { heading: '1. YOUR PATIENT ID \u2014 YOUR IDENTITY ON eSIRI PLUS', body: "When you first open eSIRI Plus, we generate a unique Patient ID just for you. It looks like this: ESR-4K9X-M2PQ\n\nThis is the only identity you need on our platform. No name. No phone number. No email. Just your Patient ID.\n\nWhat this means for you:\n\u2022 The doctor you consult with never knows your real name\n\u2022 No one at eSIRI Plus can link your consultations to your real identity\n\u2022 Your medical history is stored under your Patient ID \u2014 not your personal details\n\u2022 If you lose your Patient ID, you can recover it by answering 5 security questions you set during registration" },
      { heading: '2. WHAT INFORMATION WE COLLECT', body: "We collect only what is necessary to provide you with healthcare services.\n\nYour Health Profile (you control this):\n\u2022 Your Patient ID (generated by our system \u2014 you don't provide this)\n\u2022 Age, sex, and region (e.g., Dar es Salaam, Arusha, Mwanza)\n\u2022 Blood type and allergies \u2014 optional\n\u2022 Chronic conditions you choose to share\n\u2022 Messages and notes from your consultations\n\u2022 Medical reports you upload\n\nPayment Information:\n\u2022 Your M-Pesa phone number \u2014 used only to process your payment\n\u2022 Transaction ID and payment status\n\u2022 Which service tier you purchased\n\nTechnical Information (for security):\n\u2022 Your device type and version\n\u2022 Your IP address \u2014 used only for fraud prevention\n\u2022 Encrypted session tokens\n\nWhat we do NOT collect:\n\u2022 Your full name\n\u2022 Your national ID number\n\u2022 Your email address\n\u2022 Your home address\n\u2022 Any biometric data" },
      { heading: '3. HOW WE USE YOUR INFORMATION', body: "Your information is used for one purpose: providing you with healthcare services.\n\nSpecifically, we use it to:\n\u2022 Connect you with verified doctors and healthcare providers\n\u2022 Keep your consultation history accessible via your Patient ID\n\u2022 Process your M-Pesa payment securely\n\u2022 Keep the platform secure and prevent fraud\n\u2022 Generate your AI-assisted consultation reports\n\u2022 Improve eSIRI Plus for all patients in Tanzania\n\nWe do not use your information for advertising, marketing, or selling to third parties." },
      { heading: '4. WHO CAN SEE YOUR INFORMATION', body: "\u2022 Your doctor \u2014 Medical information you share during the consultation only\n\u2022 M-Pesa / Vodacom Tanzania \u2014 Your phone number and payment amount only\n\u2022 VideoSDK \u2014 Video call connection data \u2014 no medical information\n\u2022 eSIRI Plus team \u2014 Anonymized technical data \u2014 no personal health records\n\u2022 Tanzanian authorities \u2014 Only if required by a valid court order or law\n\nWe will never sell your information to anyone." },
      { heading: '5. HOW WE PROTECT YOUR INFORMATION', body: "We take your security seriously. Here is what we do:\n\n\u2022 Encrypted connections \u2014 All data uses TLS 1.3 encryption\n\u2022 Hashed passwords \u2014 Security question answers are hashed using PBKDF2. Originals are never stored\n\u2022 Session security \u2014 Your session token expires after 24 hours\n\u2022 Row Level Security \u2014 Each patient can only access their own records\n\u2022 No plaintext secrets \u2014 Sensitive tokens are never stored as plain text\n\u2022 Regular security audits \u2014 We test our systems regularly for vulnerabilities" },
      { heading: '6. HOW LONG WE KEEP YOUR INFORMATION', body: "\u2022 Consultation records \u2014 7 years, as required by Tanzanian healthcare regulations\n\u2022 Payment records \u2014 As required by financial regulations\n\u2022 Your Patient ID and health profile \u2014 Until you request deletion, subject to legal requirements\n\u2022 Anonymized analytics \u2014 May be kept indefinitely for service improvement\n\nYou can request deletion of your data by contacting us through the in-app support feature." },
      { heading: '7. YOUR RIGHTS', body: "As a patient using eSIRI Plus, you have the right to:\n\n\u2022 Access your full consultation history using your Patient ID\n\u2022 Correct any inaccurate health information in your records\n\u2022 Delete your data (subject to legal retention requirements)\n\u2022 Export your medical records in a portable format\n\u2022 Withdraw consent for data processing at any time\n\u2022 Lodge a complaint with the Tanzania Communications Regulatory Authority (TCRA)" },
      { heading: '8. CHILDREN\'S PRIVACY', body: 'eSIRI Plus is intended for adults aged 18 and above. If you are under 18, you may use the platform only with the supervision of a parent or guardian.' },
      { heading: '9. CHANGES TO THIS POLICY', body: 'If we make significant changes to this Privacy Policy, we will notify you through the app before the changes take effect. Continuing to use eSIRI Plus after that date means you accept the updated policy.' },
      { heading: '10. CONTACT US', body: "Have questions about your privacy?\n\n\u2022 In-app: Help & Support \u2192 Privacy\n\u2022 Email: privacy@esiri.health\n\u2022 Phone: +255 663 582 994" },
    ],
  },
  {
    key: 'security', title: 'Data Security',
    sections: [
      { heading: 'DATA SECURITY', body: 'Last Updated: February 2026' },
      { heading: 'How We Protect Your Information', body: 'eSIRI Plus uses industry-standard security measures to protect your data at every level. Your trust is the foundation of our platform \u2014 we take security seriously.' },
      { heading: 'Encryption', body: "\u2022 All data between your device and our servers uses TLS 1.3 encryption\n\u2022 Your local data is encrypted with AES-256\n\u2022 Encryption keys are securely managed\n\u2022 Sensitive tokens are never stored as plain text" },
      { heading: 'Authentication & Sessions', body: "\u2022 Your security question answers are hashed using PBKDF2 before storage \u2014 the original answers are never stored\n\u2022 Your session token expires automatically after 24 hours\n\u2022 Proactive token refresh prevents unauthorized session extension\n\u2022 After 10 failed recovery attempts, your account is temporarily locked for 30 minutes" },
      { heading: 'Database Security', body: "\u2022 Row Level Security (RLS) ensures each patient can only access their own records\n\u2022 All database queries are parameterized to prevent injection attacks\n\u2022 Database migrations are strictly controlled \u2014 no destructive changes in production" },
      { heading: 'Your Anonymity', body: "\u2022 Your Patient ID (e.g., ESR-4K9X-M2PQ) is your only identity on the platform\n\u2022 No real name, email, or national ID is collected or stored\n\u2022 Doctors see only your Patient ID \u2014 never your real identity\n\u2022 Even eSIRI Plus staff cannot link your consultations to your real identity" },
    ],
  },
  {
    key: 'terms', title: 'Terms of Service',
    sections: [
      { heading: 'TERMS OF SERVICE', body: 'Last Updated: February 2026' },
      { heading: 'Welcome to eSIRI Plus', body: "These Terms of Service explain how eSIRI Plus works and what we both agree to when you use the platform. Please read them \u2014 they're written in plain language so they're easy to understand." },
      { heading: '1. WHAT IS eSIRI PLUS?', body: "eSIRI Plus is a Tanzanian telemedicine platform that connects you with verified, licensed healthcare providers for online consultations \u2014 all from your device, without revealing your identity.\n\nWhat you can do on eSIRI Plus:\n\u2022 Have text consultations with healthcare providers (15-minute sessions, extendable)\n\u2022 Have video consultations (3 min default, rechargeable at TZS 2,500 per 3 min)\n\u2022 Access six levels of healthcare:\n  - Nurse \u2014 TZS 3,000\n  - Clinical Officer \u2014 TZS 5,000\n  - Pharmacist \u2014 TZS 5,000\n  - General Practitioner \u2014 TZS 10,000\n  - Specialist \u2014 TZS 30,000\n  - Psychologist \u2014 TZS 50,000\n\u2022 Receive AI-assisted consultation reports with QR code verification\n\u2022 Keep your complete medical history accessible via your Patient ID" },
      { heading: '2. WHO CAN USE eSIRI PLUS', body: "\u2022 You must be 18 years or older (or have parental/guardian consent if under 18)\n\u2022 You must be located in Tanzania\n\u2022 You must have the legal ability to enter into agreements\n\u2022 You must provide accurate demographic information during registration" },
      { heading: '3. YOUR PATIENT ID', body: "Your Patient ID (e.g., ESR-4K9X-M2PQ) is the key to your account. Treat it like your ATM PIN.\n\n\u2022 Keep it private \u2014 do not share it with anyone\n\u2022 Store it somewhere safe \u2014 write it down or screenshot it\n\u2022 If you lose it, use the \"Recover Patient ID\" feature and answer your 5 security questions\n\u2022 After 10 failed recovery attempts, your account will be temporarily locked for 30 minutes\n\u2022 eSIRI Plus will never ask for your Patient ID via SMS, phone call, or email" },
      { heading: '4. PAYMENTS', body: "We only accept M-Pesa (Vodacom Tanzania).\n\nHow payment works:\n1. You select your service tier\n2. An M-Pesa STK Push is sent to your phone\n3. You confirm the payment\n4. Your consultation begins only after payment is confirmed\n\nRefund Policy:\nRefunds are issued if:\n\u2022 A technical failure prevents the consultation from starting\n\u2022 The doctor becomes unavailable after payment but before the consultation\n\u2022 Your M-Pesa payment was processed but the consultation never started within 24 hours\n\nRefunds are not issued once a consultation session has started. Requests must be submitted within 7 days and are processed within 14 business days via M-Pesa reversal.\n\nDoctor Earnings:\nHealthcare providers receive 50% of every consultation fee. Earnings are paid monthly via M-Pesa." },
      { heading: '5. YOUR RESPONSIBILITIES', body: "To keep eSIRI Plus safe and useful for everyone, you agree to:\n\n\u2022 Provide accurate and honest health information during consultations\n\u2022 Use the platform for legitimate healthcare purposes only\n\u2022 Treat healthcare providers respectfully\n\u2022 Not use eSIRI Plus during a medical emergency \u2014 call 112, 114, or 115 instead\n\u2022 Not share your Patient ID with others\n\u2022 Not attempt to hack, reverse-engineer, or misuse the platform\n\u2022 Follow medical advice given by your healthcare provider" },
      { heading: '6. OUR RESPONSIBILITIES TO YOU', body: "We commit to:\n\n\u2022 Verifying all healthcare providers are licensed with the Medical Council of Tanganyika (MCT)\n\u2022 Keeping your data private and secure as described in our Privacy Policy\n\u2022 Maintaining platform uptime of 99.9%\n\u2022 Responding to support requests within 24 hours\n\u2022 Being transparent about any changes to our service or pricing" },
      { heading: '7. DISPUTE RESOLUTION', body: "If you have a dispute with us:\n\n1. First: Contact our support team \u2014 we resolve most issues quickly\n2. If unresolved: Binding arbitration under the Tanzanian Arbitration Act in Dar es Salaam\n3. If arbitration is not appropriate: Courts of Dar es Salaam, Tanzania\n\nThese Terms are governed by the laws of the United Republic of Tanzania." },
    ],
  },
  {
    key: 'medical', title: 'Medical Disclaimer',
    sections: [
      { heading: 'MEDICAL DISCLAIMER', body: 'Last Updated: February 2026' },
      { heading: '\u26a0 FOR MEDICAL EMERGENCIES, DO NOT USE THIS APP', body: "Call 112, 114, or 115 immediately, or go to your nearest hospital.\n\nEmergency hospitals in Tanzania:\n\u2022 Muhimbili National Hospital \u2014 Dar es Salaam\n\u2022 Kilimanjaro Christian Medical Centre \u2014 Moshi\n\u2022 Bugando Medical Centre \u2014 Mwanza\n\u2022 Mbeya Zonal Referral Hospital \u2014 Mbeya\n\nEmergencies include: chest pain, difficulty breathing, severe bleeding, loss of consciousness, stroke symptoms, severe allergic reactions, seizures, severe burns, thoughts of self-harm, and complications during pregnancy." },
      { heading: 'WHAT eSIRI PLUS CAN AND CANNOT DO', body: "eSIRI Plus is great for:\n\u2022 Non-urgent medical questions\n\u2022 Minor illnesses (cold, flu, mild fever, skin rashes)\n\u2022 Medication questions\n\u2022 Mental health support for mild to moderate conditions\n\u2022 Follow-up consultations for chronic conditions\n\u2022 Getting a second opinion\n\neSIRI Plus cannot replace:\n\u2022 Physical examination\n\u2022 Laboratory tests, X-rays, or ultrasounds\n\u2022 Emergency care\n\u2022 Surgery or procedures\n\u2022 In-person prenatal care\n\u2022 Hospitalization" },
      { heading: 'THE QUALITY OF ADVICE DEPENDS ON YOU', body: "The more honest and complete the information you share, the better the advice you receive. Always tell your doctor:\n\n\u2022 All your current symptoms and when they started\n\u2022 Every medication you are taking \u2014 including traditional medicines\n\u2022 All your allergies\n\u2022 Any chronic conditions (diabetes, hypertension, HIV, etc.)\n\u2022 If you are pregnant or breastfeeding\n\u2022 Any recent surgeries or hospitalizations\n\nIncomplete information can lead to incomplete advice. Your safety depends on your honesty." },
      { heading: 'ABOUT PRESCRIPTIONS', body: "\u2022 Not all medications can be prescribed via telemedicine under Tanzanian regulations\n\u2022 Controlled substances cannot be prescribed online\n\u2022 Your doctor will use medical judgment to decide what is safe to prescribe remotely\n\u2022 All prescriptions must be collected from a licensed pharmacy in Tanzania\n\u2022 eSIRI Plus does not dispense medications" },
      { heading: 'TRADITIONAL MEDICINE', body: 'We respect Tanzania\'s rich tradition of herbal and traditional medicine. Please inform your doctor if you are using any traditional remedies, as some may interact with prescribed medications. Your doctor will never dismiss your cultural practices.' },
    ],
  },
  {
    key: 'consent', title: 'Informed Consent',
    sections: [
      { heading: 'INFORMED CONSENT FOR TELEMEDICINE SERVICES', body: "Last Updated: February 2026\n\nBefore you begin using eSIRI Plus, we want to make sure you understand what you're signing up for. This is not fine print \u2014 it's important information about your healthcare." },
      { heading: '1. HOW TELEMEDICINE WORKS', body: "Telemedicine means consulting a doctor remotely using your device \u2014 via text chat or video call \u2014 instead of visiting a clinic in person.\n\nYour consultation on eSIRI Plus:\n\u2022 Takes place entirely on your device\n\u2022 Is conducted by a licensed provider who cannot physically examine you\n\u2022 Is completely anonymous \u2014 your doctor sees only your Patient ID\n\u2022 Is recorded and stored under your Patient ID for your future reference" },
      { heading: '2. THE BENEFITS', body: "\u2022 Access to quality healthcare without travel\n\u2022 Complete anonymity \u2014 your identity is never revealed\n\u2022 Consultations available in Swahili and English\n\u2022 Affordable pricing compared to physical hospital visits\n\u2022 Access to specialists you might not have locally\n\u2022 Your full medical history always available via your Patient ID" },
      { heading: '3. THE LIMITATIONS', body: "\u2022 Your doctor cannot physically examine you\n\u2022 Diagnosis is based only on information you provide\n\u2022 Some conditions cannot be safely diagnosed or treated via telemedicine\n\u2022 Technology issues may affect consultation quality\n\u2022 You may still need in-person follow-up care\n\u2022 There is no guarantee of a specific health outcome" },
      { heading: '4. YOUR RIGHTS AS A PATIENT', body: "You have the right to:\n\n\u2022 Stop using the service at any time without penalty\n\u2022 Access your full consultation history using your Patient ID\n\u2022 Refuse any treatment recommended by your provider\n\u2022 Seek a second opinion from another provider or in-person\n\u2022 Have your anonymity protected at all times\n\u2022 Report concerns about provider conduct\n\u2022 Know how your data is being used" },
      { heading: '7. EMERGENCY ACKNOWLEDGMENT', body: "\u26a0 I will NOT use eSIRI Plus for medical emergencies\n\n\u26a0 For emergencies, I will call 112, 114, or 115 or go to the nearest hospital\n\n\u26a0 I understand that delaying emergency care can cause serious harm or death" },
      { heading: '9. YOUR FINAL ACKNOWLEDGMENT', body: "By continuing to use eSIRI Plus, you confirm:\n\n\u2713 You have read and understood this consent\n\u2713 You are using eSIRI Plus voluntarily\n\u2713 You understand telemedicine's benefits and limitations\n\u2713 You are 18 years or older, or have parental/guardian consent\n\u2713 You will seek emergency care when needed (call 112/114/115)\n\u2713 You will not rely solely on telemedicine for serious or chronic conditions\n\u2713 You may withdraw consent at any time by stopping use of the app\n\nQuestions about this consent?\n\u2022 In-app: Help & Support \u2192 Consent & Legal\n\u2022 Email: consent@esiri.health\n\u2022 Phone: +255 663 582 994" },
    ],
  },
];

type Mode = 'new' | 'returning' | 'recover';

// Response from create-patient-session edge function
interface CreateSessionResponse {
  session_id: string;
  patient_id: string;
  access_token: string;
  refresh_token: string;
  expires_in: number;
  expires_at: string;
}

// Response from recover-by-id edge function
interface RecoverByIdResponse {
  session_id: string;
  access_token: string;
  refresh_token: string;
  expires_in: number;
  expires_at: string;
}

export default function PatientSetupPage() {
  return <Suspense><PatientSetupContent /></Suspense>;
}

function PatientSetupContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { setSession, setPatientSession } = useAuthStore();

  const modeParam = searchParams.get('mode');
  const [mode, setMode] = useState<Mode>(
    modeParam === 'returning' ? 'returning' : modeParam === 'recover' ? 'recover' : 'new'
  );

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [showTerms, setShowTerms] = useState(false);
  const [termsTab, setTermsTab] = useState(0);

  // New patient fields
  const [ageGroup, setAgeGroup] = useState('');
  const [sex, setSex] = useState('');
  const [region, setRegion] = useState('');

  // Returning patient
  const [patientId, setPatientId] = useState('');

  // Recovery via security questions
  const SECURITY_QUESTIONS = [
    { key: 'favorite_animal', label: "What's your favourite animal?" },
    { key: 'favorite_city', label: 'What is your favorite city?' },
    { key: 'birth_city', label: 'What city were you born in?' },
    { key: 'primary_school', label: 'What primary school did you attend?' },
    { key: 'favorite_teacher', label: 'Who was your favorite teacher?' },
  ];
  const [recoveryStep, setRecoveryStep] = useState(0);
  const [recoveryAnswers, setRecoveryAnswers] = useState<Record<string, string>>({});
  const [currentAnswer, setCurrentAnswer] = useState('');
  const [recoveredId, setRecoveredId] = useState('');

  // Result
  const [generatedId, setGeneratedId] = useState('');
  const [copied, setCopied] = useState(false);

  async function handleNewPatient(e: React.FormEvent) {
    e.preventDefault();
    setError('');

    setLoading(true);
    try {
      // 1. Create anonymous patient session (generates Patient ID server-side)
      const result = await invokeEdgeFunction<CreateSessionResponse>('create-patient-session', {});

      // 2. Store session in auth store
      const session = {
        accessToken: result.access_token,
        refreshToken: result.refresh_token,
        expiresAt: new Date(result.expires_at).getTime(),
        user: {
          id: result.patient_id,
          fullName: '',
          phone: '',
          role: 'patient' as const,
          isVerified: false,
        },
      };
      setSession(session);
      setPatientSession({
        sessionId: result.session_id,
        ageGroup,
        sex,
        region,
        allergies: [],
        chronicConditions: [],
      });

      // 3. Save demographics if any were provided
      const demographics: Record<string, string> = {};
      if (ageGroup) demographics.age = ageGroup;
      if (sex) demographics.sex = sex;
      if (region) demographics.region = region;
      if (Object.keys(demographics).length > 0) {
        try {
          await invokeEdgeFunction('update-patient-demographics', demographics, result.access_token);
        } catch {
          // Non-fatal — demographics can be updated later
        }
      }

      // 4. Show the generated Patient ID
      setGeneratedId(result.patient_id);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create patient session.');
    } finally {
      setLoading(false);
    }
  }

  async function handleReturning(e: React.FormEvent) {
    e.preventDefault();
    setError('');
    if (!patientId.trim()) { setError('Please enter your Patient ID'); return; }

    setLoading(true);
    try {
      const result = await invokeEdgeFunction<RecoverByIdResponse>('recover-by-id', {
        patient_id: patientId.trim().toUpperCase(),
      });

      const session = {
        accessToken: result.access_token,
        refreshToken: result.refresh_token,
        expiresAt: new Date(result.expires_at).getTime(),
        user: {
          id: patientId.trim().toUpperCase(),
          fullName: '',
          phone: '',
          role: 'patient' as const,
          isVerified: false,
        },
      };
      setSession(session);
      setPatientSession({
        sessionId: result.session_id,
        allergies: [],
        chronicConditions: [],
      });
      router.push('/home');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Invalid Patient ID. Please check your ID and try again.');
    } finally {
      setLoading(false);
    }
  }

  function handleRecoveryNext() {
    if (!currentAnswer.trim()) return;
    const q = SECURITY_QUESTIONS[recoveryStep];
    const updated = { ...recoveryAnswers, [q.key]: currentAnswer.trim() };
    setRecoveryAnswers(updated);
    setCurrentAnswer('');
    setError('');

    if (recoveryStep < SECURITY_QUESTIONS.length - 1) {
      setRecoveryStep(recoveryStep + 1);
    } else {
      submitRecovery(updated);
    }
  }

  async function submitRecovery(answers: Record<string, string>) {
    setLoading(true);
    try {
      const result = await invokeEdgeFunction<RecoverByIdResponse>('recover-by-questions', {
        answers,
      });
      const session = {
        accessToken: result.access_token,
        refreshToken: result.refresh_token,
        expiresAt: new Date(result.expires_at).getTime(),
        user: {
          id: result.session_id,
          fullName: '',
          phone: '',
          role: 'patient' as const,
          isVerified: false,
        },
      };
      setSession(session);
      setPatientSession({
        sessionId: result.session_id,
        allergies: [],
        chronicConditions: [],
      });
      setRecoveredId(result.session_id);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Recovery failed. Answers did not match.');
      // Reset to try again
      setRecoveryStep(0);
      setRecoveryAnswers({});
    } finally {
      setLoading(false);
    }
  }

  function copyId() {
    navigator.clipboard.writeText(generatedId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  // Show generated ID result screen
  if (generatedId) {
    return (
      <div className="pt-6">
        <Card className="p-6">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto rounded-full bg-[var(--success-green)]/10 flex items-center justify-center mb-4">
              <CheckCircle2 size={32} className="text-[var(--success-green)]" />
            </div>
            <h2 className="text-xl font-bold text-black mb-1">Welcome to eSIRI Plus!</h2>
            <p className="text-sm text-black mb-6">Your patient account has been created.</p>
          </div>

          {/* Patient ID display */}
          <div className="bg-[#FFF7ED] border-2 border-[var(--royal-gold)] rounded-xl p-4 mb-4">
            <div className="flex items-center gap-2 mb-2">
              <AlertTriangle size={18} className="text-[var(--royal-gold)]" />
              <p className="text-sm font-bold text-black">SAVE THIS ID</p>
            </div>
            <p className="text-xs text-black mb-3">
              This is your unique Patient ID. You will need it to access your records in future visits.
              Write it down or take a screenshot.
            </p>
            <div className="bg-white rounded-lg p-3 flex items-center justify-between">
              <span className="text-lg font-mono font-bold text-[var(--brand-teal)] tracking-wider">
                {generatedId}
              </span>
              <button
                onClick={copyId}
                className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-[var(--brand-teal)]/10 text-[var(--brand-teal)] text-xs font-medium"
              >
                {copied ? <CheckCircle2 size={14} /> : <Copy size={14} />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>

          <Button fullWidth size="lg" onClick={() => router.push('/home')}>
            Continue to Home <ChevronRight size={16} />
          </Button>
        </Card>
      </div>
    );
  }

  return (
    <div className="pt-2">
      {/* Mode tabs */}
      <div className="flex bg-white rounded-xl border border-[var(--card-border)] p-1 mb-4">
        {([
          { key: 'new' as Mode, label: 'New Patient', icon: UserPlus },
          { key: 'returning' as Mode, label: 'Returning', icon: KeyRound },
          { key: 'recover' as Mode, label: 'Recover ID', icon: HelpCircle },
        ]).map(({ key, label, icon: Icon }) => (
          <button
            key={key}
            onClick={() => { setMode(key); setError(''); }}
            className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-lg text-xs font-semibold transition-colors ${
              mode === key
                ? 'bg-[var(--brand-teal)] text-white shadow-sm'
                : 'text-black hover:bg-gray-50'
            }`}
          >
            <Icon size={14} />
            {label}
          </button>
        ))}
      </div>

      <Card className="p-5">
        {/* New Patient — Terms then Setup */}
        {mode === 'new' && !termsAccepted && (
          <div className="space-y-4">
            <div className="text-center mb-2">
              <Shield size={32} className="mx-auto text-[var(--brand-teal)] mb-2" />
              <h2 className="text-lg font-bold text-black">Terms & Privacy Policy</h2>
              <p className="text-sm text-[var(--subtitle-grey)]">Please review and accept to continue</p>
            </div>

            {/* Tabs */}
            <div className="flex overflow-x-auto gap-1 pb-1 -mx-1 px-1">
              {TERMS_TABS.map((tab, i) => (
                <button
                  key={tab.key}
                  onClick={() => setTermsTab(i)}
                  className={`whitespace-nowrap px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors shrink-0 ${
                    termsTab === i
                      ? 'bg-[var(--brand-teal)] text-white'
                      : 'bg-gray-100 text-[var(--subtitle-grey)] hover:bg-gray-200'
                  }`}
                >
                  {tab.title}
                </button>
              ))}
            </div>

            {/* Content */}
            <div className="bg-gray-50 rounded-xl p-4 max-h-64 overflow-y-auto text-xs text-black leading-relaxed space-y-3">
              {TERMS_TABS[termsTab].sections.map((section, i) => (
                <div key={i}>
                  {section.heading && (
                    <h4 className="font-bold text-sm mb-1">{section.heading}</h4>
                  )}
                  <p className="whitespace-pre-line">{section.body}</p>
                </div>
              ))}
            </div>

            {/* Accept checkbox */}
            <label className="flex items-start gap-3 cursor-pointer">
              <input
                type="checkbox"
                checked={showTerms}
                onChange={(e) => setShowTerms(e.target.checked)}
                className="mt-0.5 w-5 h-5 rounded border-[var(--card-border)] text-[var(--brand-teal)] focus:ring-[var(--brand-teal)] accent-[var(--brand-teal)]"
              />
              <span className="text-sm text-black">
                I have read and agree to the <strong>Privacy Policy</strong>, <strong>Terms of Service</strong>, and <strong>Medical Disclaimer</strong>
              </span>
            </label>

            <Button
              fullWidth
              size="lg"
              disabled={!showTerms}
              onClick={() => setTermsAccepted(true)}
            >
              Accept & Continue
            </Button>
          </div>
        )}

        {mode === 'new' && termsAccepted && (
          <form onSubmit={handleNewPatient} className="space-y-4">
            <div className="text-center mb-2">
              <h2 className="text-lg font-bold text-black">Health Profile</h2>
              <p className="text-sm text-[var(--subtitle-grey)]">Optional — you can skip and fill later</p>
            </div>

            <Select
              label="Age Group (optional)"
              options={AGE_GROUPS}
              placeholder="Select your age group"
              value={ageGroup}
              onChange={(e) => setAgeGroup(e.target.value)}
            />

            <Select
              label="Sex (optional)"
              options={SEX_OPTIONS}
              placeholder="Select your sex"
              value={sex}
              onChange={(e) => setSex(e.target.value)}
            />

            <Select
              label="Region (optional)"
              options={REGIONS}
              placeholder="Select your region"
              value={region}
              onChange={(e) => setRegion(e.target.value)}
            />

            <div className="bg-[var(--brand-teal)]/5 rounded-xl p-3 flex items-start gap-2">
              <Shield size={16} className="text-[var(--brand-teal)] mt-0.5 shrink-0" />
              <p className="text-xs text-black">
                Your identity stays anonymous. A unique Patient ID will be generated for you.
                No personal information is required.
              </p>
            </div>

            {error && <p className="text-sm text-[var(--error-red)] text-center">{error}</p>}

            <Button type="submit" fullWidth size="lg" loading={loading}>
              Generate My Patient ID
            </Button>
          </form>
        )}

        {/* Returning Patient */}
        {mode === 'returning' && (
          <form onSubmit={handleReturning} className="space-y-4">
            <div className="text-center mb-2">
              <div className="w-14 h-14 mx-auto rounded-full bg-[var(--brand-teal)]/10 flex items-center justify-center mb-3">
                <KeyRound size={24} className="text-[var(--brand-teal)]" />
              </div>
              <h2 className="text-lg font-bold text-black">Welcome Back</h2>
              <p className="text-sm text-black">Enter your Patient ID to access your records</p>
            </div>

            <Input
              label="Patient ID"
              placeholder="e.g. ESR-ABCD-1234"
              value={patientId}
              onChange={(e) => { setPatientId(e.target.value.toUpperCase()); setError(''); }}
              className="text-center text-lg font-mono font-bold tracking-wider"
              required
            />

            {error && <p className="text-sm text-[var(--error-red)] text-center">{error}</p>}

            <Button type="submit" fullWidth size="lg" loading={loading}>
              Access My Records
            </Button>

            <button
              type="button"
              onClick={() => setMode('recover')}
              className="w-full text-center text-sm font-medium text-[var(--brand-teal)] py-1"
            >
              Lost your Patient ID?
            </button>
          </form>
        )}

        {/* Recover via Security Questions */}
        {mode === 'recover' && (
          <div className="space-y-4">
            <div className="text-center mb-2">
              <div className="w-14 h-14 mx-auto rounded-full bg-[var(--brand-teal)]/10 flex items-center justify-center mb-3">
                <HelpCircle size={24} className="text-[var(--brand-teal)]" />
              </div>
              <h2 className="text-lg font-bold text-black">Recover Patient ID</h2>
              <p className="text-sm text-black">
                Answer your security questions to recover your Patient ID.
              </p>
            </div>

            {recoveredId ? (
              <div className="text-center py-4">
                <div className="w-16 h-16 mx-auto rounded-full bg-[var(--success-green)]/10 flex items-center justify-center mb-3">
                  <CheckCircle2 size={28} className="text-[var(--success-green)]" />
                </div>
                <h3 className="text-base font-bold text-black mb-1">ID Recovered!</h3>
                <p className="text-sm text-black mb-4">Your account has been restored.</p>
                <Button fullWidth size="lg" onClick={() => router.push('/home')}>
                  Continue to Home <ChevronRight size={16} />
                </Button>
              </div>
            ) : (
              <div className="space-y-4">
                {/* Progress */}
                <div className="flex gap-1">
                  {SECURITY_QUESTIONS.map((_, i) => (
                    <div
                      key={i}
                      className={`h-1.5 flex-1 rounded-full transition-colors ${
                        i <= recoveryStep ? 'bg-[var(--brand-teal)]' : 'bg-gray-200'
                      }`}
                    />
                  ))}
                </div>

                <p className="text-xs text-[var(--subtitle-grey)]">
                  Question {recoveryStep + 1} of {SECURITY_QUESTIONS.length}
                </p>

                <p className="text-sm font-semibold text-black">
                  {SECURITY_QUESTIONS[recoveryStep].label}
                </p>

                <Input
                  placeholder="Your answer..."
                  value={currentAnswer}
                  onChange={(e) => { setCurrentAnswer(e.target.value); setError(''); }}
                  onKeyDown={(e) => e.key === 'Enter' && handleRecoveryNext()}
                />

                {error && <p className="text-sm text-[var(--error-red)] text-center">{error}</p>}

                <Button
                  fullWidth
                  size="lg"
                  loading={loading}
                  onClick={handleRecoveryNext}
                  disabled={!currentAnswer.trim()}
                >
                  {recoveryStep < SECURITY_QUESTIONS.length - 1 ? (
                    <>Next <ArrowRight size={16} /></>
                  ) : (
                    'Recover My ID'
                  )}
                </Button>
              </div>
            )}
          </div>
        )}
      </Card>
    </div>
  );
}
