package com.esiri.esiriplus.feature.auth.screen

data class LegalSection(
    val heading: String? = null,
    val body: String,
)

enum class LegalTab(val title: String) {
    PRIVACY_POLICY("Privacy Policy"),
    DATA_SECURITY("Data Security"),
    TERMS_OF_SERVICE("Terms of Service"),
    MEDICAL_DISCLAIMER("Medical Disclaimer"),
    INFORMED_CONSENT("Informed Consent"),
}

object TermsContent {

    fun getSections(tab: LegalTab): List<LegalSection> = when (tab) {
        LegalTab.PRIVACY_POLICY -> privacyPolicy
        LegalTab.DATA_SECURITY -> dataSecurity
        LegalTab.TERMS_OF_SERVICE -> termsOfService
        LegalTab.MEDICAL_DISCLAIMER -> medicalDisclaimer
        LegalTab.INFORMED_CONSENT -> informedConsent
    }

    private val privacyPolicy = listOf(
        LegalSection(
            heading = "PRIVACY POLICY",
            body = "Last Updated: February 2026",
        ),
        LegalSection(
            heading = "We Built eSIRI Plus Around Your Privacy",
            body = "Most healthcare apps ask for your name, phone number, email, and ID. We don't. eSIRI Plus was designed from the ground up so that you can access quality healthcare in Tanzania without revealing who you are. Your health is personal — and it should stay that way.",
        ),
        LegalSection(
            heading = "1. YOUR PATIENT ID — YOUR IDENTITY ON eSIRI PLUS",
            body = """When you first open eSIRI Plus, we generate a unique Patient ID just for you. It looks like this: ESR-4K9X-M2PQ

This is the only identity you need on our platform. No name. No phone number. No email. Just your Patient ID.

What this means for you:
• The doctor you consult with never knows your real name
• No one at eSIRI Plus can link your consultations to your real identity
• Your medical history is stored under your Patient ID — not your personal details
• If you lose your Patient ID, you can recover it by answering 5 security questions you set during registration""",
        ),
        LegalSection(
            heading = "2. WHAT INFORMATION WE COLLECT",
            body = """We collect only what is necessary to provide you with healthcare services.

Your Health Profile (you control this):
• Your Patient ID (generated by our system — you don't provide this)
• Age, sex, and region (e.g., Dar es Salaam, Arusha, Mwanza)
• Blood type and allergies — optional
• Chronic conditions you choose to share
• Messages and notes from your consultations
• Medical reports you upload

Payment Information:
• Your M-Pesa phone number — used only to process your payment
• Transaction ID and payment status
• Which service tier you purchased

Technical Information (for security):
• Your Android device type and version
• Your IP address — used only for fraud prevention
• Encrypted session tokens

What we do NOT collect:
• Your full name
• Your national ID number
• Your email address
• Your home address
• Any biometric data""",
        ),
        LegalSection(
            heading = "3. HOW WE USE YOUR INFORMATION",
            body = """Your information is used for one purpose: providing you with healthcare services.

Specifically, we use it to:
• Connect you with verified doctors and healthcare providers
• Keep your consultation history accessible via your Patient ID
• Process your M-Pesa payment securely
• Keep the platform secure and prevent fraud
• Generate your AI-assisted consultation reports
• Improve eSIRI Plus for all patients in Tanzania

We do not use your information for advertising, marketing, or selling to third parties.""",
        ),
        LegalSection(
            heading = "4. WHO CAN SEE YOUR INFORMATION",
            body = """• Your doctor — Medical information you share during the consultation only
• M-Pesa / Vodacom Tanzania — Your phone number and payment amount only
• VideoSDK — Video call connection data — no medical information
• eSIRI Plus team — Anonymized technical data — no personal health records
• Tanzanian authorities — Only if required by a valid court order or law

We will never sell your information to anyone.""",
        ),
        LegalSection(
            heading = "5. HOW WE PROTECT YOUR INFORMATION",
            body = """We take your security seriously. Here is what we do:

• Encrypted connections — All data uses TLS 1.3 encryption
• Hashed passwords — Security question answers are hashed using PBKDF2. Originals are never stored
• Session security — Your session token expires after 24 hours
• Row Level Security — Each patient can only access their own records
• No plaintext secrets — Sensitive tokens are never stored as plain text
• Regular security audits — We test our systems regularly for vulnerabilities""",
        ),
        LegalSection(
            heading = "6. HOW LONG WE KEEP YOUR INFORMATION",
            body = """• Consultation records — 7 years, as required by Tanzanian healthcare regulations
• Payment records — As required by financial regulations
• Your Patient ID and health profile — Until you request deletion, subject to legal requirements
• Anonymized analytics — May be kept indefinitely for service improvement

You can request deletion of your data by contacting us through the in-app support feature.""",
        ),
        LegalSection(
            heading = "7. YOUR RIGHTS",
            body = """As a patient using eSIRI Plus, you have the right to:

• Access your full consultation history using your Patient ID
• Correct any inaccurate health information in your records
• Delete your data (subject to legal retention requirements)
• Export your medical records in a portable format
• Withdraw consent for data processing at any time
• Lodge a complaint with the Tanzania Communications Regulatory Authority (TCRA)""",
        ),
        LegalSection(
            heading = "8. CHILDREN'S PRIVACY",
            body = "eSIRI Plus is intended for adults aged 18 and above. If you are under 18, you may use the platform only with the supervision of a parent or guardian.",
        ),
        LegalSection(
            heading = "9. CHANGES TO THIS POLICY",
            body = "If we make significant changes to this Privacy Policy, we will notify you through the app before the changes take effect. Continuing to use eSIRI Plus after that date means you accept the updated policy.",
        ),
        LegalSection(
            heading = "10. CONTACT US",
            body = """Have questions about your privacy?

• In-app: Help & Support → Privacy
• Email: privacy@esiri.health
• Phone: +255 XXX XXX XXX""",
        ),
    )

    private val dataSecurity = listOf(
        LegalSection(
            heading = "DATA SECURITY",
            body = "Last Updated: February 2026",
        ),
        LegalSection(
            heading = "How We Protect Your Information",
            body = """eSIRI Plus uses industry-standard security measures to protect your data at every level. Your trust is the foundation of our platform — we take security seriously.""",
        ),
        LegalSection(
            heading = "Encryption",
            body = """• All data between your Android app and our servers uses TLS 1.3 encryption
• Your local database is encrypted with SQLCipher (AES-256)
• Encryption keys are derived from Android Keystore and stored in EncryptedSharedPreferences
• Sensitive tokens are never stored as plain text""",
        ),
        LegalSection(
            heading = "Authentication & Sessions",
            body = """• Your security question answers are hashed using PBKDF2 before storage — the original answers are never stored
• Your session token expires automatically after 24 hours
• Proactive token refresh prevents unauthorized session extension
• After 10 failed recovery attempts, your account is temporarily locked for 30 minutes""",
        ),
        LegalSection(
            heading = "Database Security",
            body = """• Row Level Security (RLS) ensures each patient can only access their own records
• All database queries are parameterized to prevent injection attacks
• Backup rules exclude encrypted database files and passphrases from cloud backups
• Database migrations are strictly controlled — no destructive changes in production""",
        ),
        LegalSection(
            heading = "Network Security",
            body = """• Interceptor chain: Proactive Refresh → Auth → Retry → Logging
• Automatic 401 retry with token refresh
• Certificate pinning for critical API endpoints
• All API calls are authenticated with short-lived tokens""",
        ),
        LegalSection(
            heading = "Your Anonymity",
            body = """• Your Patient ID (e.g., ESR-4K9X-M2PQ) is your only identity on the platform
• No real name, email, or national ID is collected or stored
• Doctors see only your Patient ID — never your real identity
• Even eSIRI Plus staff cannot link your consultations to your real identity""",
        ),
        LegalSection(
            heading = "Regular Audits",
            body = "We conduct regular security audits and vulnerability assessments to ensure our systems remain secure. If a security incident occurs, affected users will be notified promptly through the app.",
        ),
    )

    private val termsOfService = listOf(
        LegalSection(
            heading = "TERMS OF SERVICE",
            body = "Last Updated: February 2026",
        ),
        LegalSection(
            heading = "Welcome to eSIRI Plus",
            body = "These Terms of Service explain how eSIRI Plus works and what we both agree to when you use the platform. Please read them — they're written in plain language so they're easy to understand.",
        ),
        LegalSection(
            heading = "1. WHAT IS eSIRI PLUS?",
            body = """eSIRI Plus is a Tanzanian telemedicine platform that connects you with verified, licensed healthcare providers for online consultations — all from your Android phone, without revealing your identity.

What you can do on eSIRI Plus:
• Have text consultations with healthcare providers (15-minute sessions, extendable)
• Have video consultations (3 min default, rechargeable at TZS 2,500 per 3 min)
• Access six levels of healthcare:
  - Nurse — TZS 3,000
  - Clinical Officer — TZS 5,000
  - Pharmacist — TZS 5,000
  - General Practitioner — TZS 10,000
  - Specialist — TZS 30,000
  - Psychologist — TZS 50,000
• Receive AI-assisted consultation reports with QR code verification
• Keep your complete medical history accessible via your Patient ID""",
        ),
        LegalSection(
            heading = "2. WHO CAN USE eSIRI PLUS",
            body = """• You must be 18 years or older (or have parental/guardian consent if under 18)
• You must be located in Tanzania
• You must have the legal ability to enter into agreements
• You must provide accurate demographic information during registration""",
        ),
        LegalSection(
            heading = "3. YOUR PATIENT ID",
            body = """Your Patient ID (e.g., ESR-4K9X-M2PQ) is the key to your account. Treat it like your ATM PIN.

• Keep it private — do not share it with anyone
• Store it somewhere safe — write it down or screenshot it
• If you lose it, use the "Recover Patient ID" feature and answer your 5 security questions
• After 10 failed recovery attempts, your account will be temporarily locked for 30 minutes
• eSIRI Plus will never ask for your Patient ID via SMS, phone call, or email""",
        ),
        LegalSection(
            heading = "4. PAYMENTS",
            body = """We only accept M-Pesa (Vodacom Tanzania).

How payment works:
1. You select your service tier
2. An M-Pesa STK Push is sent to your phone
3. You confirm the payment
4. Your consultation begins only after payment is confirmed

Refund Policy:
Refunds are issued if:
• A technical failure prevents the consultation from starting
• The doctor becomes unavailable after payment but before the consultation
• Your M-Pesa payment was processed but the consultation never started within 24 hours

Refunds are not issued once a consultation session has started. Requests must be submitted within 7 days and are processed within 14 business days via M-Pesa reversal.

Doctor Earnings:
Healthcare providers receive 50% of every consultation fee. Earnings are paid monthly via M-Pesa.""",
        ),
        LegalSection(
            heading = "5. YOUR RESPONSIBILITIES",
            body = """To keep eSIRI Plus safe and useful for everyone, you agree to:

• Provide accurate and honest health information during consultations
• Use the platform for legitimate healthcare purposes only
• Treat healthcare providers respectfully
• Not use eSIRI Plus during a medical emergency — call 112, 114, or 115 instead
• Not share your Patient ID with others
• Not attempt to hack, reverse-engineer, or misuse the platform
• Follow medical advice given by your healthcare provider""",
        ),
        LegalSection(
            heading = "6. OUR RESPONSIBILITIES TO YOU",
            body = """We commit to:

• Verifying all healthcare providers are licensed with the Medical Council of Tanganyika (MCT)
• Keeping your data private and secure as described in our Privacy Policy
• Maintaining platform uptime of 99.9%
• Responding to support requests within 24 hours
• Being transparent about any changes to our service or pricing""",
        ),
        LegalSection(
            heading = "7. HEALTHCARE PROVIDERS",
            body = "All providers on eSIRI Plus are independent licensed professionals. They are not eSIRI Plus employees. eSIRI Plus verifies their credentials and facilitates your connection — but the medical relationship is directly between you and your provider.",
        ),
        LegalSection(
            heading = "8. WHAT WE ARE NOT LIABLE FOR",
            body = """• We are not responsible for medical outcomes, diagnoses, or treatment decisions
• We are not liable for service disruptions caused by your internet connection, M-Pesa downtime, or events beyond our control
• Our total liability is limited to the amount you paid for the specific consultation in question""",
        ),
        LegalSection(
            heading = "9. DISPUTE RESOLUTION",
            body = """If you have a dispute with us:

1. First: Contact our support team — we resolve most issues quickly
2. If unresolved: Binding arbitration under the Tanzanian Arbitration Act in Dar es Salaam
3. If arbitration is not appropriate: Courts of Dar es Salaam, Tanzania

These Terms are governed by the laws of the United Republic of Tanzania.""",
        ),
        LegalSection(
            heading = "10. CHANGES TO THESE TERMS",
            body = "We will give you 30 days' notice via in-app notification before making significant changes. If you disagree, you may stop using eSIRI Plus and request account deletion.",
        ),
        LegalSection(
            heading = "11. CONTACT US",
            body = """• In-app: Help & Support
• Email: support@esiri.health
• Phone: +255 XXX XXX XXX
• Address: Dar es Salaam, Tanzania""",
        ),
    )

    private val medicalDisclaimer = listOf(
        LegalSection(
            heading = "MEDICAL DISCLAIMER",
            body = "Last Updated: February 2026",
        ),
        LegalSection(
            heading = "⚠ FOR MEDICAL EMERGENCIES, DO NOT USE THIS APP",
            body = """Call 112, 114, or 115 immediately, or go to your nearest hospital.

Emergency hospitals in Tanzania:
• Muhimbili National Hospital — Dar es Salaam
• Kilimanjaro Christian Medical Centre — Moshi
• Bugando Medical Centre — Mwanza
• Mbeya Zonal Referral Hospital — Mbeya

Emergencies include: chest pain, difficulty breathing, severe bleeding, loss of consciousness, stroke symptoms, severe allergic reactions, seizures, severe burns, thoughts of self-harm, and complications during pregnancy.""",
        ),
        LegalSection(
            heading = "WHAT eSIRI PLUS CAN AND CANNOT DO",
            body = """eSIRI Plus is great for:
• Non-urgent medical questions
• Minor illnesses (cold, flu, mild fever, skin rashes)
• Medication questions
• Mental health support for mild to moderate conditions
• Follow-up consultations for chronic conditions
• Getting a second opinion

eSIRI Plus cannot replace:
• Physical examination
• Laboratory tests, X-rays, or ultrasounds
• Emergency care
• Surgery or procedures
• In-person prenatal care
• Hospitalization""",
        ),
        LegalSection(
            heading = "THE QUALITY OF ADVICE DEPENDS ON YOU",
            body = """The more honest and complete the information you share, the better the advice you receive. Always tell your doctor:

• All your current symptoms and when they started
• Every medication you are taking — including traditional medicines
• All your allergies
• Any chronic conditions (diabetes, hypertension, HIV, etc.)
• If you are pregnant or breastfeeding
• Any recent surgeries or hospitalizations

Incomplete information can lead to incomplete advice. Your safety depends on your honesty.""",
        ),
        LegalSection(
            heading = "WHEN TO SEEK IN-PERSON CARE",
            body = """Please visit a hospital or clinic if:

• Your symptoms worsen or do not improve within 48–72 hours
• Your doctor on eSIRI Plus recommends in-person evaluation
• You need a physical exam, blood test, X-ray, or ultrasound
• You are pregnant and experiencing complications
• You have a chronic condition that requires regular monitoring
• You need medication that requires a physical prescription""",
        ),
        LegalSection(
            heading = "ABOUT PRESCRIPTIONS",
            body = """• Not all medications can be prescribed via telemedicine under Tanzanian regulations
• Controlled substances cannot be prescribed online
• Your doctor will use medical judgment to decide what is safe to prescribe remotely
• All prescriptions must be collected from a licensed pharmacy in Tanzania
• eSIRI Plus does not dispense medications""",
        ),
        LegalSection(
            heading = "TRADITIONAL MEDICINE",
            body = "We respect Tanzania's rich tradition of herbal and traditional medicine. Please inform your doctor if you are using any traditional remedies, as some may interact with prescribed medications. Your doctor will never dismiss your cultural practices.",
        ),
        LegalSection(
            heading = "MENTAL HEALTH SERVICES",
            body = """For mild to moderate mental health concerns, eSIRI Plus can help. However:

• Severe mental health conditions require in-person therapy
• If you are in crisis or having thoughts of self-harm, go to the nearest hospital psychiatric unit immediately""",
        ),
        LegalSection(
            heading = "NO DOCTOR-PATIENT RELATIONSHIP WITH eSIRI PLUS",
            body = "The doctor-patient relationship exists only between you and the individual healthcare provider you consult with. eSIRI Plus is the technology platform that connects you — we are not your healthcare provider.",
        ),
    )

    private val informedConsent = listOf(
        LegalSection(
            heading = "INFORMED CONSENT FOR TELEMEDICINE SERVICES",
            body = "Last Updated: February 2026\n\nBefore you begin using eSIRI Plus, we want to make sure you understand what you're signing up for. This is not fine print — it's important information about your healthcare.",
        ),
        LegalSection(
            heading = "1. HOW TELEMEDICINE WORKS",
            body = """Telemedicine means consulting a doctor remotely using your Android phone — via text chat or video call — instead of visiting a clinic in person.

Your consultation on eSIRI Plus:
• Takes place entirely on your Android device
• Is conducted by a licensed provider who cannot physically examine you
• Is completely anonymous — your doctor sees only your Patient ID
• Is recorded and stored under your Patient ID for your future reference""",
        ),
        LegalSection(
            heading = "2. THE BENEFITS YOU'RE GETTING",
            body = """• Access to quality healthcare without travel
• Complete anonymity — your identity is never revealed
• Consultations available in Swahili and English
• Affordable pricing compared to physical hospital visits
• Access to specialists you might not have locally
• Your full medical history always available via your Patient ID""",
        ),
        LegalSection(
            heading = "3. THE LIMITATIONS YOU SHOULD KNOW",
            body = """• Your doctor cannot physically examine you
• Diagnosis is based only on information you provide
• Some conditions cannot be safely diagnosed or treated via telemedicine
• Technology issues may affect consultation quality
• You may still need in-person follow-up care
• There is no guarantee of a specific health outcome""",
        ),
        LegalSection(
            heading = "4. YOUR RIGHTS AS A PATIENT",
            body = """You have the right to:

• Stop using the service at any time without penalty
• Access your full consultation history using your Patient ID
• Refuse any treatment recommended by your provider
• Seek a second opinion from another provider or in-person
• Have your anonymity protected at all times
• Report concerns about provider conduct
• Know how your data is being used""",
        ),
        LegalSection(
            heading = "5. YOUR COMMITMENTS AS A PATIENT",
            body = """You agree to:

• Provide complete and honest health information
• Not use eSIRI Plus for medical emergencies
• Follow up with in-person care when recommended
• Keep your Patient ID private and secure
• Treat healthcare providers with respect
• Use your own M-Pesa number for payments""",
        ),
        LegalSection(
            heading = "6. PAYMENT UNDERSTANDING",
            body = """You understand that:

• Consultation fees must be paid via M-Pesa before the session begins
• Fees range from TZS 3,000 to TZS 50,000 depending on the provider type
• Payments are non-refundable once a consultation starts
• Video call recharge costs TZS 2,500 per additional 3 minutes""",
        ),
        LegalSection(
            heading = "7. EMERGENCY ACKNOWLEDGMENT",
            body = """⚠ I will NOT use eSIRI Plus for medical emergencies

⚠ For emergencies, I will call 112, 114, or 115 or go to the nearest hospital

⚠ I understand that delaying emergency care can cause serious harm or death""",
        ),
        LegalSection(
            heading = "8. DATA CONSENT",
            body = """You consent to:

• Your health information being stored securely under your Patient ID
• Your consultation records being retained for 7 years as required by Tanzanian law
• Your M-Pesa phone number being shared with Vodacom Tanzania for payment processing only
• Anonymized data being used to improve the platform""",
        ),
        LegalSection(
            heading = "9. YOUR FINAL ACKNOWLEDGMENT",
            body = """By continuing to use eSIRI Plus, you confirm:

✓ You have read and understood this consent
✓ You are using eSIRI Plus voluntarily
✓ You understand telemedicine's benefits and limitations
✓ You are 18 years or older, or have parental/guardian consent
✓ You will seek emergency care when needed (call 112/114/115)
✓ You will not rely solely on telemedicine for serious or chronic conditions
✓ You may withdraw consent at any time by stopping use of the app

Questions about this consent?
• In-app: Help & Support → Consent & Legal
• Email: consent@esiri.health
• Medical Council of Tanganyika: +255 22 XXX XXXX""",
        ),
    )
}
