#!/usr/bin/env python3
"""
Converts the mtaa JSON (Kalebu/mtaa) into a SQL migration that seeds
tz_locations with every region → district → ward → street.

Usage:
    python scripts/generate_tz_locations_seed.py

Reads:  tmp/tanzania_json.py (the raw JSON file from the mtaa repo)
Writes: supabase/migrations/20260416140000_tz_locations_full_seed.sql
"""
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tmp" / "tanzania_json.py"
OUT = ROOT / "supabase" / "migrations" / "20260416140000_tz_locations_full_seed.sql"

def sql_escape(s: str) -> str:
    # strip whitespace, normalize case (Title Case), escape quotes
    cleaned = re.sub(r"\s+", " ", s).strip()
    return cleaned.replace("'", "''")

def clean_name(raw: str) -> str:
    # Mtaa data sometimes has "Shinyanga\ncbd" style names with embedded newlines
    # and odd capitalization. We normalize to stripped whitespace while keeping
    # the original display case.
    return re.sub(r"\s+", " ", raw).strip()

def main() -> int:
    if not SRC.exists():
        print(f"ERROR: source file not found at {SRC}", file=sys.stderr)
        print("Download it first with:")
        print("  curl -sL https://raw.githubusercontent.com/Kalebu/mtaa/main/mtaa/tanzania_json.py -o tmp/tanzania_json.py")
        return 1

    with open(SRC, "r", encoding="utf-8") as f:
        data = json.load(f)

    regions = sorted(data.keys())
    print(f"Loaded {len(regions)} regions")

    chunks: list[str] = []
    chunks.append(
        "-- ============================================================================\n"
        "-- Full Tanzania location seed (generated by scripts/generate_tz_locations_seed.py)\n"
        "-- Source: https://github.com/Kalebu/mtaa (which pulls from HackEAC/tanzania-locations-db)\n"
        "--\n"
        "-- Populates every region, district, ward, and street (mtaa) into tz_locations.\n"
        "-- Idempotent via ON CONFLICT (parent_id, name) DO NOTHING — safe to re-run.\n"
        "-- ============================================================================\n\n"
    )

    wards_total = 0
    streets_total = 0

    for region_name in regions:
        region = data[region_name]
        r_clean = clean_name(region_name)
        districts = region.get("districts", {}) or {}

        chunks.append(f"-- ── Region: {r_clean} ────────────────────────────────\n")
        chunks.append("DO $$\n")
        chunks.append("DECLARE\n")
        chunks.append("    r UUID;\n")
        chunks.append("    d UUID;\n")
        chunks.append("    w UUID;\n")
        chunks.append("BEGIN\n")

        # Get or insert region (case-insensitive by name) — safe on populated tables
        # because (parent_id, name) UNIQUE treats NULL parent_id as distinct.
        chunks.append(
            f"    SELECT id INTO r FROM tz_locations\n"
            f"        WHERE level = 'region' AND lower(name) = lower('{sql_escape(r_clean)}') LIMIT 1;\n"
            f"    IF r IS NULL THEN\n"
            f"        INSERT INTO tz_locations (name, level) VALUES ('{sql_escape(r_clean)}', 'region') RETURNING id INTO r;\n"
            f"    END IF;\n"
        )

        for district_name, district in districts.items():
            d_clean = clean_name(district_name)
            if not d_clean or not isinstance(district, dict):
                continue
            wards = district.get("wards", {}) or {}
            if not isinstance(wards, dict):
                wards = {}

            chunks.append(
                f"    SELECT id INTO d FROM tz_locations\n"
                f"        WHERE level = 'district' AND parent_id = r AND lower(name) = lower('{sql_escape(d_clean)}') LIMIT 1;\n"
                f"    IF d IS NULL THEN\n"
                f"        INSERT INTO tz_locations (name, level, parent_id) VALUES ('{sql_escape(d_clean)}', 'district', r) RETURNING id INTO d;\n"
                f"    END IF;\n"
            )

            # Batch-insert wards for this district
            if wards:
                ward_values = []
                for ward_name in wards.keys():
                    w_clean = clean_name(ward_name)
                    if not w_clean:
                        continue
                    ward_values.append(f"('{sql_escape(w_clean)}', 'ward', d)")
                if ward_values:
                    wards_total += len(ward_values)
                    chunks.append(
                        "    INSERT INTO tz_locations (name, level, parent_id) VALUES\n        " +
                        ",\n        ".join(ward_values) +
                        "\n        ON CONFLICT (parent_id, name) DO NOTHING;\n"
                    )

            # For each ward, look up its id and insert its streets.
            # We emit separate ward-by-ward blocks only when the ward has streets.
            for ward_name, ward in wards.items():
                w_clean = clean_name(ward_name)
                if not w_clean or not isinstance(ward, dict):
                    continue
                streets = ward.get("streets", {}) or {}
                if not streets:
                    continue

                # Flatten: keys of `streets` are top-level streets; their values
                # are arrays of sub-streets. We treat both as individual street
                # rows (can be deduplicated by the unique constraint).
                street_names: set[str] = set()
                for top_street, sub_streets in streets.items():
                    top_clean = clean_name(top_street)
                    if top_clean:
                        street_names.add(top_clean)
                    if isinstance(sub_streets, list):
                        for s in sub_streets:
                            s_clean = clean_name(s)
                            if s_clean:
                                street_names.add(s_clean)

                if not street_names:
                    continue

                chunks.append(
                    f"    SELECT id INTO w FROM tz_locations\n"
                    f"        WHERE level = 'ward' AND parent_id = d AND lower(name) = lower('{sql_escape(w_clean)}') LIMIT 1;\n"
                    f"    IF w IS NOT NULL THEN\n"
                )
                street_values = [f"('{sql_escape(n)}', 'street', w)" for n in sorted(street_names)]
                streets_total += len(street_values)
                # Emit in chunks of 100 to keep the SQL statement size reasonable
                for i in range(0, len(street_values), 100):
                    batch = street_values[i:i + 100]
                    chunks.append(
                        "        INSERT INTO tz_locations (name, level, parent_id) VALUES\n            " +
                        ",\n            ".join(batch) +
                        "\n            ON CONFLICT (parent_id, name) DO NOTHING;\n"
                    )
                chunks.append("    END IF;\n")

        chunks.append("END $$;\n\n")

    chunks.append(
        f"-- Totals seeded by this migration:\n"
        f"--   Regions  : {len(regions)}\n"
        f"--   Wards    : {wards_total}\n"
        f"--   Streets  : {streets_total}\n"
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.writelines(chunks)

    size_kb = OUT.stat().st_size // 1024
    print(f"Generated {OUT} ({size_kb} KB)")
    print(f"  Regions : {len(regions)}")
    print(f"  Wards   : {wards_total}")
    print(f"  Streets : {streets_total}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
