// functions/generate-doctor-performance-report/index.ts
// Generates an AI-powered doctor performance report.
// Aggregates consultations, ratings, earnings, and flags for a doctor,
// then uses ChatGPT to produce a professional performance summary.
// Auth: admin, hr only. Rate limit: LIMITS.payment (stricter).

import { handlePreflight } from "../_shared/cors.ts";
import { validateAuth, requireRole } from "../_shared/auth.ts";
import { errorResponse, successResponse, ValidationError } from "../_shared/errors.ts";
import { getServiceClient } from "../_shared/supabase.ts";
import { LIMITS } from "../_shared/rateLimit.ts";
import { logEvent, getClientIp } from "../_shared/logger.ts";

const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY")!;

Deno.serve(async (req: Request) => {
  const origin = req.headers.get("origin");
  const preflight = handlePreflight(req);
  if (preflight) return preflight;

  try {
    const auth = await validateAuth(req);
    requireRole(auth, "admin", "hr");

    await LIMITS.payment(auth.userId!);

    const body = await req.json();
    const doctorId = body.doctor_id;
    if (typeof doctorId !== "string" || !doctorId.trim()) {
      throw new ValidationError("doctor_id is required");
    }

    const supabase = getServiceClient();

    // 1. Fetch doctor profile
    const { data: doctor } = await supabase
      .from("doctor_profiles")
      .select("doctor_id, full_name, specialty, specialist_field, years_experience, average_rating, total_ratings, is_verified, is_available, created_at")
      .eq("doctor_id", doctorId)
      .single();

    if (!doctor) {
      throw new ValidationError("Doctor not found");
    }

    // 2. Consultation stats (detailed)
    const { data: allConsultations } = await supabase
      .from("consultations")
      .select("consultation_id, patient_session_id, status, service_type, session_start_time, session_end_time")
      .eq("doctor_id", doctorId);

    const totalConsultations = (allConsultations ?? []).length;
    const completedConsultations = (allConsultations ?? []).filter((c: any) => c.status === "completed").length;
    const cancelledConsultations = (allConsultations ?? []).filter((c: any) => c.status === "cancelled").length;
    const uniquePatients = new Set((allConsultations ?? []).map((c: any) => c.patient_session_id)).size;

    // Service type breakdown
    const serviceTypeCounts: Record<string, number> = {};
    for (const c of allConsultations ?? []) {
      const st = c.service_type ?? "unknown";
      serviceTypeCounts[st] = (serviceTypeCounts[st] || 0) + 1;
    }

    // Average consultation duration (for completed consultations with timestamps)
    let avgDurationMin = 0;
    const durationsMin: number[] = [];
    for (const c of allConsultations ?? []) {
      if (c.session_start_time && c.session_end_time) {
        const start = new Date(c.session_start_time).getTime();
        const end = new Date(c.session_end_time).getTime();
        if (end > start) durationsMin.push((end - start) / 60000);
      }
    }
    if (durationsMin.length > 0) {
      avgDurationMin = Math.round(durationsMin.reduce((a, b) => a + b, 0) / durationsMin.length);
    }

    // Reports generated by this doctor
    const { count: reportsGenerated } = await supabase
      .from("consultation_reports")
      .select("report_id", { count: "exact", head: true })
      .eq("doctor_id", doctorId);

    // Prescriptions written by this doctor
    const consultationIds = (allConsultations ?? []).map((c: any) => c.consultation_id);
    let prescriptionCount = 0;
    if (consultationIds.length > 0) {
      const { count: rxCount } = await supabase
        .from("prescriptions")
        .select("prescription_id", { count: "exact", head: true })
        .in("consultation_id", consultationIds);
      prescriptionCount = rxCount ?? 0;
    }

    // 3. Rating breakdown
    const { data: ratings } = await supabase
      .from("doctor_ratings")
      .select("rating, comment, is_flagged")
      .eq("doctor_id", doctorId);

    const ratingBreakdown = [0, 0, 0, 0, 0]; // 1-5 stars
    let flaggedCount = 0;
    const recentComments: string[] = [];

    for (const r of ratings ?? []) {
      if (r.rating >= 1 && r.rating <= 5) ratingBreakdown[r.rating - 1]++;
      if (r.is_flagged) flaggedCount++;
      if (r.comment && recentComments.length < 10) recentComments.push(r.comment);
    }

    // 4. Earnings (if available)
    const { data: earnings } = await supabase
      .from("doctor_earnings")
      .select("amount, currency")
      .eq("doctor_id", doctorId);

    const totalEarnings = (earnings ?? []).reduce(
      (sum: number, e: any) => sum + (Number(e.amount) || 0),
      0
    );
    const currency = earnings?.[0]?.currency ?? "TZS";

    // 5. Admin actions on this doctor
    const { data: adminActions } = await supabase
      .from("admin_logs")
      .select("action, details, created_at")
      .eq("target_id", doctorId)
      .eq("target_type", "doctor_profile")
      .order("created_at", { ascending: false })
      .limit(10);

    // Build the ChatGPT prompt
    const prompt = `
You are a professional HR analytics assistant. Generate a structured doctor performance report based on the data below.

DOCTOR PROFILE:
- Name: ${doctor.full_name}
- Specialty: ${doctor.specialty}${doctor.specialist_field ? ` (${doctor.specialist_field})` : ""}
- Years of Experience: ${doctor.years_experience}
- Verified: ${doctor.is_verified ? "Yes" : "No"}
- Currently Available: ${doctor.is_available ? "Yes" : "No"}
- Joined: ${doctor.created_at}

CONSULTATION STATISTICS:
- Total Consultations: ${totalConsultations}
- Completed: ${completedConsultations}
- Cancelled: ${cancelledConsultations}
- Completion Rate: ${totalConsultations ? Math.round((completedConsultations / totalConsultations) * 100) : 0}%
- Unique Patients Served: ${uniquePatients}
- Average Consultation Duration: ${avgDurationMin > 0 ? `${avgDurationMin} minutes` : "Not enough data"}
- By Service Type: ${Object.entries(serviceTypeCounts).map(([k, v]) => `${k}=${v}`).join(", ") || "N/A"}

CLINICAL OUTPUT:
- Consultation Reports Generated: ${reportsGenerated ?? 0}
- Prescriptions Written: ${prescriptionCount}

RATINGS:
- Average Rating: ${doctor.average_rating ?? 0}/5
- Total Ratings: ${doctor.total_ratings ?? 0}
- Rating Breakdown: 1★=${ratingBreakdown[0]}, 2★=${ratingBreakdown[1]}, 3★=${ratingBreakdown[2]}, 4★=${ratingBreakdown[3]}, 5★=${ratingBreakdown[4]}
- Flagged Reviews: ${flaggedCount}
- Recent Patient Comments: ${recentComments.length > 0 ? recentComments.join(" | ") : "None"}

FINANCIAL:
- Total Earnings: ${totalEarnings} ${currency}

ADMIN ACTIONS:
${(adminActions ?? []).map((a: any) => `- ${a.action} on ${a.created_at}`).join("\n") || "None recorded"}

Generate a professional performance report with these EXACT JSON keys:
1. "executive_summary" — 3-5 sentence overview of this doctor's performance, strengths, and areas for attention.
2. "consultation_analysis" — Analysis of their consultation volume, completion rate, and patterns. 2-4 sentences.
3. "patient_satisfaction" — Assessment of patient ratings, comments, and any flagged concerns. 2-4 sentences.
4. "financial_overview" — Brief financial performance summary. 1-3 sentences.
5. "recommendations" — 2-4 actionable recommendations for this doctor or for HR to consider.
6. "risk_flags" — Any concerns about flagged reviews, high cancellation rates, admin warnings, etc. "None" if no concerns.

Use professional HR language. Base analysis ONLY on the provided data. Do not fabricate information.
Respond ONLY with valid JSON, no markdown, no backticks.
`;

    const aiRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${OPENAI_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content: "You are an HR analytics AI. Respond only with valid JSON. No preamble, no markdown.",
          },
          { role: "user", content: prompt },
        ],
        max_tokens: 2000,
        temperature: 0.3,
      }),
    });

    if (!aiRes.ok) {
      const errText = await aiRes.text();
      console.error(`[doctor-performance-report] OpenAI error (${aiRes.status}): ${errText}`);
      throw new Error("AI report generation failed");
    }

    const aiData = await aiRes.json();
    let report: Record<string, string>;

    try {
      const rawText = aiData.choices[0].message.content as string;
      const cleaned = rawText.replace(/```json|```/g, "").trim();
      report = JSON.parse(cleaned);
    } catch {
      throw new Error("Failed to parse AI report output");
    }

    await logEvent({
      function_name: "generate-doctor-performance-report",
      level: "info",
      user_id: auth.userId,
      action: "doctor_performance_report_generated",
      metadata: { doctor_id: doctorId, doctor_name: doctor.full_name },
      ip_address: getClientIp(req),
    });

    return successResponse(
      {
        doctor_name: doctor.full_name,
        doctor_id: doctorId,
        generated_at: new Date().toISOString(),
        report,
      },
      200,
      origin
    );
  } catch (err) {
    return errorResponse(err, origin);
  }
});
